# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Victus\PycharmProjects\Gme\rating.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Rating(object):
    def setupUi(self, Rating):
        Rating.setObjectName("Rating")
        Rating.resize(432, 470)
        Rating.setMinimumSize(QtCore.QSize(370, 468))
        Rating.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Rating.setBaseSize(QtCore.QSize(2, 0))
        Rating.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Rating.setMouseTracking(False)
        Rating.setAccessibleName("")
        Rating.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Rating)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setStyleSheet("QWidget{\n"
"color: #333;\n"
"background-color: rgb(212, 220, 255)\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #b1b1b1;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #b1b1b1;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(208, 208, 208); \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #888;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(212, 220, 255)\n"
"border-radius: 10px;\n"
"border: 1px solid #b1b1b1;\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #b1b1b1;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"QTextEdit{\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #b1b1b1;\n"
"}\n"
"")
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.back = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back.setFont(font)
        self.back.setIconSize(QtCore.QSize(28, 25))
        self.back.setObjectName("back")
        self.verticalLayout_2.addWidget(self.back)
        Rating.setCentralWidget(self.centralwidget)

        self.retranslateUi(Rating)
        QtCore.QMetaObject.connectSlotsByName(Rating)

    def retranslateUi(self, Rating):
        _translate = QtCore.QCoreApplication.translate
        Rating.setWindowTitle(_translate("Rating", "Филворды"))
        self.label.setHtml(_translate("Rating", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.back.setText(_translate("Rating", "ВЕРНУТЬСЯ В ГЛАВНОЕ МЕНЮ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Rating = QtWidgets.QMainWindow()
    ui = Ui_Rating()
    ui.setupUi(Rating)
    Rating.show()
    sys.exit(app.exec_())
