# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Victus\PycharmProjects\Gme\rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rules(object):
    def setupUi(self, rules):
        rules.setObjectName("rules")
        rules.resize(559, 519)
        rules.setMinimumSize(QtCore.QSize(370, 468))
        rules.setMaximumSize(QtCore.QSize(16777215, 16777215))
        rules.setBaseSize(QtCore.QSize(2, 0))
        rules.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        rules.setMouseTracking(False)
        rules.setAccessibleName("")
        rules.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(rules)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setStyleSheet("QWidget{\n"
"color: #333;\n"
"background-color: rgb(212, 220, 255)\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #b1b1b1;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #b1b1b1;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(208, 208, 208); \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #888;\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 30, 20, 30)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sssss = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sssss.sizePolicy().hasHeightForWidth())
        self.sssss.setSizePolicy(sizePolicy)
        self.sssss.setMinimumSize(QtCore.QSize(0, 0))
        self.sssss.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.sssss.setFont(font)
        self.sssss.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.sssss.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sssss.setStyleSheet("")
        self.sssss.setFrame(False)
        self.sssss.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.sssss.setAlignment(QtCore.Qt.AlignCenter)
        self.sssss.setClearButtonEnabled(False)
        self.sssss.setObjectName("sssss")
        self.verticalLayout.addWidget(self.sssss)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        rules.setCentralWidget(self.centralwidget)

        self.retranslateUi(rules)
        QtCore.QMetaObject.connectSlotsByName(rules)

    def retranslateUi(self, rules):
        _translate = QtCore.QCoreApplication.translate
        rules.setWindowTitle(_translate("rules", "Филворды"))
        self.sssss.setText(_translate("rules", ""))


