# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Victus/PycharmProjects/Gme/zanovo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zanovo_2(object):
    def setupUi(self, zanovo_2):
        zanovo_2.setObjectName("zanovo_2")
        zanovo_2.resize(374, 276)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(zanovo_2.sizePolicy().hasHeightForWidth())
        zanovo_2.setSizePolicy(sizePolicy)
        zanovo_2.setMinimumSize(QtCore.QSize(374, 276))
        zanovo_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        zanovo_2.setBaseSize(QtCore.QSize(2, 0))
        zanovo_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        zanovo_2.setMouseTracking(False)
        zanovo_2.setAccessibleName("")
        zanovo_2.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(zanovo_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setStyleSheet("QWidget{\n"
"color: #333;\n"
"background-color: rgb(212, 220, 255)\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #b1b1b1;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #b1b1b1;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(208, 208, 208); \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #888;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(212, 220, 255)\n"
"border-radius: 10px;\n"
"border: 1px solid #b1b1b1;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.zanovo = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zanovo.sizePolicy().hasHeightForWidth())
        self.zanovo.setSizePolicy(sizePolicy)
        self.zanovo.setMinimumSize(QtCore.QSize(0, 0))
        self.zanovo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.zanovo.setFont(font)
        self.zanovo.setStyleSheet("")
        self.zanovo.setObjectName("zanovo")
        self.verticalLayout.addWidget(self.zanovo)
        self.glmenu = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glmenu.sizePolicy().hasHeightForWidth())
        self.glmenu.setSizePolicy(sizePolicy)
        self.glmenu.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.glmenu.setFont(font)
        self.glmenu.setObjectName("glmenu")
        self.verticalLayout.addWidget(self.glmenu)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit.sizePolicy().hasHeightForWidth())
        self.exit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.verticalLayout.addWidget(self.exit)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 30)
        self.verticalLayout.setStretch(2, 30)
        self.verticalLayout.setStretch(3, 30)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        zanovo_2.setCentralWidget(self.centralwidget)

        self.retranslateUi(zanovo_2)
        QtCore.QMetaObject.connectSlotsByName(zanovo_2)

    def retranslateUi(self, zanovo_2):
        _translate = QtCore.QCoreApplication.translate
        zanovo_2.setWindowTitle(_translate("zanovo_2", "Филворды"))
        self.label.setText(_translate("zanovo_2", "УРОВЕНЬ ПРОЙДЕН"))
        self.zanovo.setText(_translate("zanovo_2", "ПОВТОРИТЬ"))
        self.glmenu.setText(_translate("zanovo_2", "ВЫБОР УРОВНЯ"))
        self.exit.setText(_translate("zanovo_2", "ВЫЙТИ"))
